//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_group_memory_config")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: Option<String>,
    pub group_id: Option<String>,
    pub success_strategy: Option<i32>,
    pub success_strategy_value: Option<i64>,
    pub fail_strategy: Option<i32>,
    pub fail_strategy_value: Option<i64>,
    pub memory_day: Option<i32>,
    pub inbound_cover: Option<i32>,
    pub outbound_cover: Option<i32>,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


