//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_phone_location")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    pub ruid: Option<String>,
    pub username: Option<String>,
    pub domain: Option<String>,
    pub contact: Option<String>,
    pub received: Option<String>,
    pub path: Option<String>,
    pub expires: Option<DateTime>,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))")] // 根据实际精度调整
    pub q: Option<Decimal>,
    pub callid: Option<String>,
    pub cseq: Option<i32>,
    pub last_modified: Option<DateTime>,
    pub flags: Option<i32>,
    pub cflags: Option<i32>,
    pub user_agent: Option<String>,
    pub socket: Option<String>,
    pub methods: Option<i32>,
    pub instance: Option<String>,
    pub reg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


