//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_call_device")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub call_id: String,
    pub device_id: String,
    pub agent_key: Option<String>,
    pub agent_name: Option<String>,
    pub device_type: String,
    pub cdr_type: Option<String>,
    pub from_agent: Option<String>,
    pub caller: Option<String>,
    pub called: Option<String>,
    pub display: Option<String>,
    pub called_location: Option<String>,
    pub caller_location: Option<String>,
    pub call_time: Option<DateTime>,
    pub ring_start_time: Option<DateTime>,
    pub ring_end_time: Option<DateTime>,
    pub answer_time: Option<DateTime>,
    pub bridge_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub talk_time: Option<i64>,
    pub record_start_time: Option<DateTime>,
    pub record_time: Option<i64>,
    pub sip_protocol: Option<String>,
    pub record: Option<String>,
    pub record2: Option<String>,
    pub record3: Option<String>,
    pub channel_name: Option<String>,
    pub hangup_cause: Option<String>,
    pub ring_cause: Option<String>,
    pub sip_status: Option<String>,
    pub ext1: Option<String>,
    pub ext2: Option<String>,
    pub month: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


