//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_vdn_schedule")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: Option<String>,
    pub name: Option<String>,
    pub level_value: Option<i32>,
    pub r#type: Option<String>,
    pub start_day: Option<String>,
    pub end_day: Option<String>,
    pub start_time: Option<String>,
    pub end_time: Option<String>,
    pub mon: Option<bool>,
    pub tue: Option<bool>,
    pub wed: Option<bool>,
    pub thu: Option<bool>,
    pub fri: Option<bool>,
    pub sat: Option<bool>,
    pub sun: Option<bool>,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


