//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_skill_group")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: Option<String>,
    pub skill_id: Option<String>,
    pub group_id: Option<String>,
    pub level_value: Option<i32>,
    pub rank_type: Option<String>,
    pub rank_value_start: Option<i32>,
    pub rank_value: Option<i32>,
    pub match_type: Option<String>,
    pub share_value: Option<i32>,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


