//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{
    AgentPasswordTypeEnum, BillingTypeEnum, CompanyStatusEnum, PayTypeEnum,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_company")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// PK
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    /// 名称
    pub name: String,
    /// 父企业ID
    pub id_path: String,
    /// 父企业
    pub pid: String,
    /// 简称
    pub company_code: String,
    /// 时区概念(默认是GTM+8)
    pub gmt: i32,
    /// 联系人
    pub contact: String,
    /// 电话
    pub phone: String,
    /// 金额
    pub balance: i64,
    /// 1:呼出计费,2:呼入计费,3:双向计费,0:全免费
    pub bill_type: BillingTypeEnum,
    /// 0:预付费;1:后付费
    pub pay_type: PayTypeEnum,
    /// 隐藏客户号码(0:不隐藏;1:隐藏)
    pub hidden_customer: bool,
    /// 坐席密码等级(1:不限制 2:数字和字母 3:大小写字母和数字组合)
    pub secret_type: AgentPasswordTypeEnum,
    /// 验证秘钥
    pub secret_key: Option<String>,
    /// IVR通道数
    pub ivr_limit: i32,
    /// 开通坐席
    pub agent_limit: i32,
    /// 开通技能组
    pub group_limit: i32,
    /// 单技能组中坐席上限
    pub group_agent_limit: i32,
    /// 录音保留x个月
    pub record_storage: i32,
    /// 话单回调通知
    pub notify_url: String,
    /// 扩展字段1
    #[sea_orm(column_type = "Text", nullable)]
    pub ext1: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext2: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext3: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext4: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext5: Option<String>,
    pub status: CompanyStatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
