//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_call_detail")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub call_id: String,
    pub device_id: Option<String>,
    pub detail_index: Option<i32>,
    pub cdr_type: String,
    pub transfer_type: Option<String>,
    pub transfer_id: Option<String>,
    pub caller: Option<String>,
    pub called: Option<String>,
    pub display: Option<String>,
    pub agent_key: Option<String>,
    pub agent_name: Option<String>,
    pub group_id: Option<String>,
    pub start_time: Option<DateTime>,
    pub answer_time: Option<DateTime>,
    pub end_time: Option<i64>,
    pub talk_time: Option<i32>,
    pub ring_time: Option<i32>,
    pub record_url: Option<String>,
    pub reason: Option<String>,
    pub ext1: Option<String>,
    pub ext2: Option<String>,
    pub month: i32,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


