//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "cti", table_name = "cti_call_dtmf")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub dtmf_key: Option<String>,
    pub process_id: Option<String>,
    pub call_id: Option<String>,
    pub dtmf_time: Option<DateTime>,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}


