//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod system_access_token;
pub mod system_dict_data;
pub mod system_dict_type;
pub mod system_menu;
pub mod system_role;
pub mod system_role_menu;
pub mod system_tenant;
pub mod system_user_role;
pub mod system_users;
