//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, SmsChannelEnum, SmsTemplateTypeEnum};
use daoyi_common_support::utils::templates::parse_template_content_params;
use daoyi_common_support::vo::system_vo::{
    SmsTemplateRespVO, SmsTemplateSaveReqVO, SmsTemplateUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_sms_template")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: SmsTemplateTypeEnum,
    pub status: CommonStatusEnum,
    pub code: String,
    pub name: String,
    pub content: String,
    pub params: Vec<String>,
    pub remark: Option<String>,
    pub api_template_id: String,
    pub channel_id: String,
    pub channel_code: SmsChannelEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<SmsTemplateSaveReqVO> for ActiveModel {
    fn from(value: SmsTemplateSaveReqVO) -> Self {
        let params = parse_template_content_params(&value.content);
        Self {
            r#type: Set(value.r#type),
            status: Set(value.status),
            code: Set(value.code),
            name: Set(value.name),
            content: Set(value.content),
            params: Set(params),
            remark: Set(value.remark),
            api_template_id: Set(value.api_template_id),
            channel_id: Set(value.channel_id),
            ..Default::default()
        }
    }
}

impl From<SmsTemplateUpdateReqVO> for ActiveModel {
    fn from(value: SmsTemplateUpdateReqVO) -> Self {
        let params = parse_template_content_params(&value.content);
        Self {
            id: Unchanged(value.id),
            r#type: Set(value.r#type),
            status: Set(value.status),
            code: Set(value.code),
            name: Set(value.name),
            content: Set(value.content),
            params: Set(params),
            remark: Set(value.remark),
            api_template_id: Set(value.api_template_id),
            channel_id: Set(value.channel_id),
            ..Default::default()
        }
    }
}

impl From<Model> for SmsTemplateRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            r#type: value.r#type,
            status: value.status,
            code: value.code,
            name: value.name,
            content: value.content,
            params: value.params,
            remark: value.remark,
            api_template_id: value.api_template_id,
            channel_id: value.channel_id,
            channel_code: value.channel_code,
            create_time: value.create_time,
        }
    }
}
