//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, SexEnum};
use daoyi_common_support::vo::system_vo::{UserRespVO, UserSaveReqVo, UserSimpleRespVo, UserVO};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub password: String,
    pub nickname: String,
    pub remark: Option<String>,
    pub dept_id: Option<String>,
    pub post_ids: Option<Vec<String>>,
    pub email: Option<String>,
    pub mobile: Option<String>,
    pub sex: Option<SexEnum>,
    pub avatar: Option<String>,
    pub status: CommonStatusEnum,
    pub login_ip: Option<String>,
    pub login_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<UserSaveReqVo> for ActiveModel {
    fn from(value: UserSaveReqVo) -> Self {
        let mut active_model = Self::new();
        if value.id.is_some() {
            active_model.id = Unchanged(value.id.unwrap());
        }
        active_model.username = Set(value.username);
        active_model.nickname = Set(value.nickname);
        active_model.remark = Set(value.remark);
        active_model.dept_id = Set(value.dept_id);
        active_model.post_ids = Set(value.post_ids);
        active_model.email = Set(value.email);
        active_model.mobile = Set(value.mobile);
        active_model.sex = Set(value.sex);
        active_model.avatar = Set(value.avatar);
        active_model.password = Set(value.password);
        active_model
    }
}

impl Model {
    pub fn convert_simple_vo(self, dept_name: Option<String>) -> UserSimpleRespVo {
        UserSimpleRespVo {
            dept_id: self.dept_id,
            dept_name,
            id: self.id,
            nickname: self.nickname,
        }
    }
    pub fn convert_vo(self, dept_name: Option<String>) -> UserRespVO {
        UserRespVO {
            avatar: self.avatar,
            create_time: self.create_time,
            dept_id: self.dept_id,
            dept_name,
            email: self.email,
            id: self.id,
            login_date: self.login_date,
            login_ip: self.login_ip,
            mobile: self.mobile,
            nickname: self.nickname,
            post_ids: self.post_ids,
            remark: self.remark,
            sex: self.sex,
            status: self.status,
            username: self.username,
        }
    }
}

impl From<Model> for UserVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            nickname: value.nickname,
            avatar: value.avatar,
            dept_id: value.dept_id,
            username: value.username,
            email: value.email,
        }
    }
}

impl From<Model> for UserRespVO {
    fn from(value: Model) -> Self {
        Self {
            avatar: value.avatar,
            create_time: value.create_time,
            dept_id: value.dept_id,
            dept_name: None,
            email: value.email,
            id: value.id,
            login_date: value.login_date,
            login_ip: value.login_ip,
            mobile: value.mobile,
            nickname: value.nickname,
            post_ids: value.post_ids,
            remark: value.remark,
            sex: value.sex,
            status: value.status,
            username: value.username,
        }
    }
}
