//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::UserTypeEnum;
use daoyi_common_support::vo::system_vo::operate_log_vo::{
    OperateLogCreateReqDTO, OperateLogRespVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::Set;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_operate_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub trace_id: String,
    pub user_id: Option<String>,
    pub user_type: UserTypeEnum,
    pub r#type: String,
    pub sub_type: String,
    pub biz_id: String,
    pub action: String,
    pub success: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra: Json,
    pub request_method: Option<String>,
    pub request_url: Option<String>,
    pub user_ip: Option<String>,
    pub user_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for OperateLogRespVO {
    fn from(value: Model) -> Self {
        Self {
            action: value.action,
            biz_id: value.biz_id,
            create_time: value.create_time,
            extra: value.extra,
            id: value.id,
            request_method: value.request_method,
            request_url: value.request_url,
            sub_type: value.sub_type,
            trace_id: value.trace_id,
            r#type: value.r#type,
            user_agent: value.user_agent,
            user_id: value.user_id,
            user_ip: value.user_ip,
            user_name: Default::default(),
            user_type: value.user_type,
        }
    }
}

impl From<OperateLogCreateReqDTO> for ActiveModel {
    fn from(value: OperateLogCreateReqDTO) -> Self {
        Self {
            trace_id: Set(value.trace_id),
            user_id: Set(value.user_id),
            user_type: Set(value.user_type),
            r#type: Set(value.r#type),
            biz_id: Set(value.biz_id),
            action: Set(value.action),
            extra: Set(value.extra),
            request_method: Set(value.request_method),
            user_ip: Set(value.user_ip),
            user_agent: Set(value.user_agent),
            ..Default::default()
        }
    }
}
