//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, DataScopeEnum, RoleTypeEnum};
use daoyi_common_support::vo::system_vo::RoleSaveReqVo;
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_role")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub code: String,
    pub sort: i32,
    pub data_scope: DataScopeEnum,
    pub data_scope_dept_ids: Vec<String>,
    pub status: CommonStatusEnum,
    pub r#type: RoleTypeEnum,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<RoleSaveReqVo> for ActiveModel {
    fn from(value: RoleSaveReqVo) -> Self {
        let mut active_model = Self::new();
        if value.id.is_some() {
            active_model.id = Unchanged(value.id.unwrap());
        }
        active_model.code = Set(value.code);
        active_model.name = Set(value.name);
        active_model.remark = Set(value.remark);
        active_model.sort = Set(value.sort);
        active_model.status = Set(value.status);
        active_model
    }
}
