//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, MenuTypeEnum};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_menu")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub permission: String,
    pub r#type: MenuTypeEnum,
    pub sort: i32,
    pub parent_id: String,
    pub path: Option<String>,
    pub icon: Option<String>,
    pub component: Option<String>,
    pub component_name: Option<String>,
    pub status: CommonStatusEnum,
    pub visible: bool,
    pub keep_alive: bool,
    pub always_show: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
