//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_mail_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: Option<String>,
    pub user_type: Option<String>,
    pub to_mail: String,
    pub account_id: String,
    pub from_mail: String,
    pub template_id: String,
    pub template_code: String,
    pub template_nickname: Option<String>,
    pub template_title: String,
    pub template_content: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub template_params: Json,
    pub send_status: String,
    pub send_time: Option<DateTime>,
    pub send_message_id: Option<String>,
    pub send_exception: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
