//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::DeptRespVo;
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_dept")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub parent_id: String,
    pub sort: i32,
    pub leader_user_id: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub status: CommonStatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for DeptRespVo {
    fn from(value: Model) -> Self {
        Self {
            create_time: value.create_time,
            email: value.email,
            id: value.id,
            leader_user_id: value.leader_user_id,
            name: value.name,
            parent_id: value.parent_id,
            phone: value.phone,
            sort: value.sort,
            status: value.status,
        }
    }
}
