//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, DataScopeEnum, RoleTypeEnum};
use daoyi_common_support::vo::system_vo::{RoleRespVO, RoleSaveReqVO, RoleUpdateReqVO};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_role")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub code: String,
    pub sort: i32,
    pub data_scope: DataScopeEnum,
    pub data_scope_dept_ids: Vec<String>,
    pub status: CommonStatusEnum,
    pub r#type: RoleTypeEnum,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for RoleRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            code: value.code,
            sort: value.sort,
            data_scope: value.data_scope,
            data_scope_dept_ids: value.data_scope_dept_ids,
            status: value.status,
            r#type: value.r#type,
            remark: value.remark,
            create_time: value.create_time,
        }
    }
}

impl From<RoleSaveReqVO> for ActiveModel {
    fn from(value: RoleSaveReqVO) -> Self {
        Self {
            code: Set(value.code),
            name: Set(value.name),
            remark: Set(value.remark),
            sort: Set(value.sort.into_inner()),
            status: Set(value.status),
            ..Default::default()
        }
    }
}

impl From<RoleUpdateReqVO> for ActiveModel {
    fn from(value: RoleUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            code: Set(value.code),
            name: Set(value.name),
            remark: Set(value.remark),
            sort: Set(value.sort.into_inner()),
            status: Set(value.status),
            ..Default::default()
        }
    }
}
