//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, NoticeTypeEnum};
use daoyi_common_support::vo::system_vo::{NoticeRespVO, NoticeSaveReqVO, NoticeUpdateReqVO};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_notice")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub r#type: NoticeTypeEnum,
    pub status: CommonStatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for NoticeRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            title: value.title,
            content: value.content,
            r#type: value.r#type,
            status: value.status,
            create_time: value.create_time,
        }
    }
}

impl From<NoticeSaveReqVO> for ActiveModel {
    fn from(value: NoticeSaveReqVO) -> Self {
        Self {
            content: Set(value.content),
            title: Set(value.title),
            r#type: Set(value.r#type),
            status: Set(value.status),
            ..Default::default()
        }
    }
}

impl From<NoticeUpdateReqVO> for ActiveModel {
    fn from(value: NoticeUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            content: Set(value.content),
            title: Set(value.title),
            r#type: Set(value.r#type),
            status: Set(value.status),
            ..Default::default()
        }
    }
}
