//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::{
    DictTypeRespVO, DictTypeSaveReqVO, DictTypeSimpleRespVO, DictTypeUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_dict_type")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub r#type: String,
    pub status: CommonStatusEnum,
    pub remark: Option<String>,
    pub deleted_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for DictTypeRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            r#type: value.r#type,
            status: value.status,
            remark: value.remark,
            create_time: value.create_time,
        }
    }
}

impl From<Model> for DictTypeSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            r#type: value.r#type,
        }
    }
}

impl From<DictTypeSaveReqVO> for ActiveModel {
    fn from(value: DictTypeSaveReqVO) -> Self {
        Self {
            name: Set(value.name),
            r#type: Set(value.r#type),
            status: Set(value.status),
            remark: Set(value.remark),
            ..Default::default()
        }
    }
}

impl From<DictTypeUpdateReqVO> for ActiveModel {
    fn from(value: DictTypeUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            name: Set(value.name),
            r#type: Set(value.r#type),
            status: Set(value.status),
            remark: Set(value.remark),
            ..Default::default()
        }
    }
}
