//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::{
    SmsChannelRespVO, SmsChannelSaveReqVO, SmsChannelSimpleRespVO, SmsChannelUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_sms_channel")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub signature: String,
    pub code: String,
    pub status: CommonStatusEnum,
    pub remark: Option<String>,
    pub api_key: String,
    pub api_secret: Option<String>,
    pub callback_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<SmsChannelSaveReqVO> for ActiveModel {
    fn from(value: SmsChannelSaveReqVO) -> Self {
        Self {
            signature: Set(value.signature),
            code: Set(value.code),
            status: Set(value.status),
            remark: Set(value.remark),
            api_key: Set(value.api_key),
            api_secret: Set(value.api_secret),
            callback_url: Set(value.callback_url),
            ..Default::default()
        }
    }
}

impl From<SmsChannelUpdateReqVO> for ActiveModel {
    fn from(value: SmsChannelUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            signature: Set(value.signature),
            code: Set(value.code),
            status: Set(value.status),
            remark: Set(value.remark),
            api_key: Set(value.api_key),
            api_secret: Set(value.api_secret),
            callback_url: Set(value.callback_url),
            ..Default::default()
        }
    }
}

impl From<Model> for SmsChannelRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            signature: value.signature,
            code: value.code,
            status: value.status,
            remark: value.remark,
            api_key: value.api_key,
            api_secret: value.api_secret,
            callback_url: value.callback_url,
            create_time: value.create_time,
        }
    }
}

impl From<Model> for SmsChannelSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            signature: value.signature,
            code: value.code,
        }
    }
}
