//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::vo::system_vo::{
    MailAccountRespVO, MailAccountSaveReqVO, MailAccountSimpleRespVO, MailAccountUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_mail_account")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub mail: String,
    pub username: String,
    pub password_plaintext: String,
    pub host: String,
    pub port: i32,
    pub ssl_enable: bool,
    pub starttls_enable: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for MailAccountRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            mail: value.mail,
            username: value.username,
            password: value.password_plaintext,
            host: value.host,
            port: value.port,
            ssl_enable: value.ssl_enable,
            starttls_enable: value.starttls_enable,
            create_time: value.create_time,
        }
    }
}

impl From<Model> for MailAccountSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            mail: value.mail,
        }
    }
}

impl From<MailAccountSaveReqVO> for ActiveModel {
    fn from(value: MailAccountSaveReqVO) -> Self {
        Self {
            mail: Set(value.mail),
            username: Set(value.username),
            password_plaintext: Set(value.password),
            host: Set(value.host),
            port: Set(value.port),
            ssl_enable: Set(value.ssl_enable),
            starttls_enable: Set(value.starttls_enable),
            ..Default::default()
        }
    }
}

impl From<MailAccountUpdateReqVO> for ActiveModel {
    fn from(value: MailAccountUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            mail: Set(value.mail),
            username: Set(value.username),
            password_plaintext: Set(value.password),
            host: Set(value.host),
            port: Set(value.port),
            ssl_enable: Set(value.ssl_enable),
            starttls_enable: Set(value.starttls_enable),
            ..Default::default()
        }
    }
}
