//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{LoginLogTypeEnum, LoginResultEnum, UserTypeEnum};
use daoyi_common_support::vo::system_vo::login_log_vo::{LoginLogCreateReqDTO, LoginLogRespVO};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::Set;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_login_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub log_type: LoginLogTypeEnum,
    pub trace_id: String,
    pub user_id: String,
    pub user_type: UserTypeEnum,
    pub username: String,
    pub result: LoginResultEnum,
    pub user_ip: String,
    pub user_agent: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<LoginLogCreateReqDTO> for ActiveModel {
    fn from(value: LoginLogCreateReqDTO) -> Self {
        Self {
            log_type: Set(value.log_type),
            trace_id: Set(value.trace_id),
            user_id: Set(value.user_id),
            user_type: Set(value.user_type),
            username: Set(value.username),
            result: Set(value.result),
            user_ip: Set(value.user_ip),
            user_agent: Set(value.user_agent),
            ..Default::default()
        }
    }
}

impl From<Model> for LoginLogRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            log_type: value.log_type,
            trace_id: value.trace_id,
            user_id: value.user_id,
            user_type: value.user_type,
            username: value.username,
            result: value.result,
            user_ip: value.user_ip,
            user_agent: value.user_agent,
            create_time: value.create_time,
        }
    }
}
