//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::{
    PostRespVo, PostSaveReqVO, PostSimpleRespVo, PostUpdateReqVo,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_post")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub code: String,
    pub name: String,
    pub sort: i32,
    pub status: CommonStatusEnum,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for PostSimpleRespVo {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
        }
    }
}

impl From<Model> for PostRespVo {
    fn from(value: Model) -> Self {
        Self {
            code: value.code,
            create_time: value.create_time,
            id: value.id,
            name: value.name,
            remark: value.remark,
            sort: value.sort,
            status: value.status,
        }
    }
}

impl From<PostSaveReqVO> for ActiveModel {
    fn from(value: PostSaveReqVO) -> Self {
        Self {
            code: Set(value.code),
            name: Set(value.name),
            remark: Set(value.remark),
            sort: Set(value.sort.into_inner()),
            status: Set(value.status),
            ..Default::default()
        }
    }
}

impl From<PostUpdateReqVo> for ActiveModel {
    fn from(value: PostUpdateReqVo) -> Self {
        Self {
            id: Unchanged(value.id),
            code: Set(value.code),
            name: Set(value.name),
            remark: Set(value.remark),
            sort: Set(value.sort.into_inner()),
            status: Set(value.status),
            ..Default::default()
        }
    }
}
