//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, ID_ROOT};
use daoyi_common_support::vo::system_vo::{
    DeptRespVo, DeptSaveReqVO, DeptSimpleRespVO, DeptUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_dept")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub parent_id: String,
    pub sort: i32,
    pub leader_user_id: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub status: CommonStatusEnum,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<DeptSaveReqVO> for ActiveModel {
    fn from(value: DeptSaveReqVO) -> Self {
        Self {
            email: Set(value.email),
            leader_user_id: Set(value.leader_user_id),
            name: Set(value.name),
            parent_id: Set(value.parent_id.unwrap_or(String::from(ID_ROOT))),
            phone: Set(value.phone),
            sort: Set(value.sort),
            status: Set(value.status),
            ..Default::default()
        }
    }
}

impl From<DeptUpdateReqVO> for ActiveModel {
    fn from(value: DeptUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            email: Set(value.email),
            leader_user_id: Set(value.leader_user_id),
            name: Set(value.name),
            parent_id: Set(value.parent_id.unwrap_or(String::from(ID_ROOT))),
            phone: Set(value.phone),
            sort: Set(value.sort),
            status: Set(value.status),
            ..Default::default()
        }
    }
}

impl From<Model> for DeptRespVo {
    fn from(value: Model) -> Self {
        Self {
            create_time: value.create_time,
            email: value.email,
            id: value.id,
            leader_user_id: value.leader_user_id,
            name: value.name,
            parent_id: value.parent_id,
            phone: value.phone,
            sort: value.sort,
            status: value.status,
        }
    }
}

impl From<Model> for DeptSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            parent_id: value.parent_id,
        }
    }
}
