//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::{
    SmsTemplateRespVO, SmsTemplateSaveReqVO, SmsTemplateUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_sms_template")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: String,
    pub status: CommonStatusEnum,
    pub code: String,
    pub name: String,
    pub content: String,
    pub params: String,
    pub remark: Option<String>,
    pub api_template_id: String,
    pub channel_id: String,
    pub channel_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<SmsTemplateSaveReqVO> for ActiveModel {
    fn from(value: SmsTemplateSaveReqVO) -> Self {
        Self {
            r#type: Set(value.r#type.to_string()),
            status: Set(value.status),
            code: Set(value.code),
            name: Set(value.name),
            content: Set(value.content),
            params: Set("[]".to_string()), // TODO: Parse params from content
            remark: Set(value.remark),
            api_template_id: Set(value.api_template_id),
            channel_id: Set(value.channel_id),
            // channel_code: Set(value.channel_code), // channel_code is not in VO? Need to look up?
            // Wait, channel_code is in Model but not in SaveReqVO.
            // Java Service looks up Channel to get code.
            // So ActiveModel here will be incomplete.
            // Service needs to handle this.
            ..Default::default()
        }
    }
}

impl From<SmsTemplateUpdateReqVO> for ActiveModel {
    fn from(value: SmsTemplateUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            r#type: Set(value.r#type.to_string()),
            status: Set(value.status),
            code: Set(value.code),
            name: Set(value.name),
            content: Set(value.content),
            params: Set("[]".to_string()), // TODO: Parse params
            remark: Set(value.remark),
            api_template_id: Set(value.api_template_id),
            channel_id: Set(value.channel_id),
            ..Default::default()
        }
    }
}

impl From<Model> for SmsTemplateRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            r#type: value.r#type.parse().unwrap_or(0),
            status: value.status,
            code: value.code,
            name: value.name,
            content: value.content,
            params: serde_json::from_str(&value.params).unwrap_or_default(),
            remark: value.remark,
            api_template_id: value.api_template_id,
            channel_id: value.channel_id,
            channel_code: value.channel_code,
            create_time: value.create_time,
        }
    }
}
