//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, NotifyTemplateTypeEnum};
use daoyi_common_support::utils::templates::parse_template_content_params;
use daoyi_common_support::vo::system_vo::{
    NotifyTemplateRespVo, NotifyTemplateSaveReqVO, NotifyTemplateUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_notify_template")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub code: String,
    pub nickname: String,
    pub content: String,
    pub r#type: NotifyTemplateTypeEnum,
    pub params: Vec<String>,
    pub status: CommonStatusEnum,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for NotifyTemplateRespVo {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            code: value.code,
            nickname: value.nickname,
            content: value.content,
            r#type: value.r#type,
            params: value.params,
            status: value.status,
            remark: value.remark,
            create_time: value.create_time,
        }
    }
}

impl From<NotifyTemplateUpdateReqVO> for ActiveModel {
    fn from(value: NotifyTemplateUpdateReqVO) -> Self {
        let params = parse_template_content_params(&value.content);
        Self {
            id: Unchanged(value.id),
            name: Set(value.name),
            code: Set(value.code),
            nickname: Set(value.nickname),
            content: Set(value.content),
            params: Set(params),
            r#type: Set(value.r#type),
            status: Set(value.status),
            remark: Set(value.remark),
            ..Default::default()
        }
    }
}

impl From<NotifyTemplateSaveReqVO> for ActiveModel {
    fn from(value: NotifyTemplateSaveReqVO) -> Self {
        let params = parse_template_content_params(&value.content);
        Self {
            name: Set(value.name),
            code: Set(value.code),
            nickname: Set(value.nickname),
            content: Set(value.content),
            params: Set(params),
            r#type: Set(value.r#type),
            status: Set(value.status),
            remark: Set(value.remark),
            ..Default::default()
        }
    }
}
