//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::{TenantRespVO, TenantSaveReqVo, TenantUpdateReqVo};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_tenant")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub contact_user_id: Option<String>,
    pub contact_name: String,
    pub contact_mobile: Option<String>,
    pub status: CommonStatusEnum,
    pub websites: Option<Vec<String>>,
    pub package_id: String,
    pub expire_time: DateTime,
    pub account_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl From<TenantUpdateReqVo> for ActiveModel {
    fn from(value: TenantUpdateReqVo) -> Self {
        let mut active_model = Self::new();
        active_model.id = Unchanged(value.id);
        active_model.name = Set(value.name);
        active_model.contact_name = Set(value.contact_name);
        active_model.contact_mobile = Set(value.contact_mobile);
        active_model.status = Set(value.status);
        active_model.websites = Set(value.websites);
        active_model.package_id = Set(value.package_id);
        active_model.expire_time = Set(value.expire_time);
        active_model.account_count = Set(value.account_count);
        active_model
    }
}
impl From<TenantSaveReqVo> for ActiveModel {
    fn from(value: TenantSaveReqVo) -> Self {
        let mut active_model = Self::new();
        active_model.name = Set(value.name);
        active_model.contact_name = Set(value.contact_name);
        active_model.contact_mobile = Set(value.contact_mobile);
        active_model.status = Set(value.status);
        active_model.websites = Set(value.websites);
        active_model.package_id = Set(value.package_id);
        active_model.expire_time = Set(value.expire_time);
        active_model.account_count = Set(value.account_count);
        active_model
    }
}
impl From<Model> for TenantRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            contact_user_id: value.contact_user_id,
            contact_name: value.contact_name,
            contact_mobile: value.contact_mobile,
            status: value.status,
            websites: value.websites,
            package_id: value.package_id,
            expire_time: value.expire_time,
            account_count: value.account_count,
        }
    }
}
