//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::vo::system_vo::AuthLoginRespVO;
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_access_token")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub access_token: String,
    #[serde(with = "daoyi_common_support::serde::datetime_format")]
    pub expires_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for AuthLoginRespVO {
    fn from(value: Model) -> Self {
        Self {
            tenant_id: value.tenant_id,
            user_id: value.user_id,
            access_token: value.access_token,
            expires_time: value.expires_time,
        }
    }
}
