//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::{
    DictDataRespVO, DictDataSaveReqVO, DictDataSimpleRespVO, DictDataUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_dict_data")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub sort: i32,
    pub label: String,
    pub value: String,
    pub dict_type: String,
    pub status: CommonStatusEnum,
    pub color_type: Option<String>,
    pub css_class: Option<String>,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
impl From<Model> for DictDataRespVO {
    fn from(value: Model) -> Self {
        Self {
            dict_type: value.dict_type,
            id: value.id,
            label: value.label,
            remark: value.remark,
            sort: value.sort,
            status: value.status,
            value: value.value,
            color_type: value.color_type,
            create_time: value.create_time,
            css_class: value.css_class,
        }
    }
}
impl From<Model> for DictDataSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            dict_type: value.dict_type,
            label: value.label,
            value: value.value,
            color_type: value.color_type,
            css_class: value.css_class,
        }
    }
}

impl From<DictDataSaveReqVO> for ActiveModel {
    fn from(value: DictDataSaveReqVO) -> Self {
        Self {
            sort: Set(value.sort),
            label: Set(value.label),
            value: Set(value.value),
            dict_type: Set(value.dict_type),
            status: Set(value.status),
            color_type: Set(value.color_type),
            css_class: Set(value.css_class),
            remark: Set(value.remark),
            ..Default::default()
        }
    }
}

impl From<DictDataUpdateReqVO> for ActiveModel {
    fn from(value: DictDataUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            sort: Set(value.sort),
            label: Set(value.label),
            value: Set(value.value),
            status: Set(value.status),
            color_type: Set(value.color_type),
            css_class: Set(value.css_class),
            remark: Set(value.remark),
            ..Default::default()
        }
    }
}
