//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, MenuTypeEnum};
use daoyi_common_support::vo::system_vo::{MenuRespVO, MenuSaveVO, MenuSimpleRespVo, MenuUpdateVO};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_menu")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub permission: Option<String>,
    pub r#type: MenuTypeEnum,
    pub sort: i32,
    pub parent_id: String,
    pub path: Option<String>,
    pub icon: Option<String>,
    pub component: Option<String>,
    pub component_name: Option<String>,
    pub status: CommonStatusEnum,
    pub visible: bool,
    pub keep_alive: bool,
    pub always_show: bool,
    pub api: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for MenuSimpleRespVo {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            r#type: value.r#type,
            parent_id: value.parent_id,
        }
    }
}
impl From<Model> for MenuRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
            permission: value.permission,
            r#type: value.r#type,
            sort: value.sort,
            parent_id: value.parent_id,
            path: value.path,
            icon: value.icon,
            component: value.component,
            component_name: value.component_name,
            status: value.status,
            visible: value.visible,
            keep_alive: value.keep_alive,
            always_show: value.always_show,
            create_time: value.create_time,
        }
    }
}

impl From<MenuSaveVO> for ActiveModel {
    fn from(value: MenuSaveVO) -> Self {
        Self {
            name: Set(value.name),
            permission: Set(value.permission),
            r#type: Set(value.r#type),
            sort: Set(value.sort),
            parent_id: Set(value.parent_id),
            path: Set(value.path),
            icon: Set(value.icon),
            component: Set(value.component),
            component_name: Set(value.component_name),
            status: Set(value.status),
            visible: Set(value.visible),
            keep_alive: Set(value.keep_alive),
            always_show: Set(value.always_show),
            ..Default::default()
        }
    }
}

impl From<MenuUpdateVO> for ActiveModel {
    fn from(value: MenuUpdateVO) -> Self {
        Self {
            id: Unchanged(value.id),
            name: Set(value.name),
            permission: Set(value.permission),
            r#type: Set(value.r#type),
            sort: Set(value.sort),
            parent_id: Set(value.parent_id),
            path: Set(value.path),
            icon: Set(value.icon),
            component: Set(value.component),
            component_name: Set(value.component_name),
            status: Set(value.status),
            visible: Set(value.visible),
            keep_alive: Set(value.keep_alive),
            always_show: Set(value.always_show),
            ..Default::default()
        }
    }
}
