//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{CommonStatusEnum, SexEnum};
use daoyi_common_support::vo::system_vo::{
    UserRespVO, UserSaveReqVO, UserSimpleRespVo, UserUpdateReqVO, UserVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub password: String,
    pub nickname: String,
    pub remark: Option<String>,
    pub dept_id: Option<String>,
    pub post_ids: Option<Vec<String>>,
    pub email: Option<String>,
    pub mobile: Option<String>,
    pub sex: Option<SexEnum>,
    pub avatar: Option<String>,
    pub status: CommonStatusEnum,
    pub login_ip: Option<String>,
    pub login_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<UserSaveReqVO> for ActiveModel {
    fn from(value: UserSaveReqVO) -> Self {
        Self {
            username: Set(value.username),
            nickname: Set(value.nickname),
            remark: Set(value.remark),
            dept_id: Set(value.dept_id),
            post_ids: Set(value.post_ids),
            email: Set(value.email),
            mobile: Set(value.mobile),
            sex: Set(value.sex),
            avatar: Set(value.avatar),
            password: Set(value.password),
            ..Default::default()
        }
    }
}

impl From<UserUpdateReqVO> for ActiveModel {
    fn from(value: UserUpdateReqVO) -> Self {
        Self {
            id: Unchanged(value.id),
            username: Set(value.username),
            nickname: Set(value.nickname),
            remark: Set(value.remark),
            dept_id: Set(value.dept_id),
            post_ids: Set(value.post_ids),
            email: Set(value.email),
            mobile: Set(value.mobile),
            sex: Set(value.sex),
            avatar: Set(value.avatar),
            password: Set(value.password),
            ..Default::default()
        }
    }
}

impl Model {
    pub fn convert_simple_vo(self, dept_name: Option<String>) -> UserSimpleRespVo {
        UserSimpleRespVo {
            dept_id: self.dept_id,
            dept_name,
            id: self.id,
            nickname: self.nickname,
        }
    }
    pub fn convert_vo(self, dept_name: Option<String>) -> UserRespVO {
        UserRespVO {
            avatar: self.avatar,
            create_time: self.create_time,
            dept_id: self.dept_id,
            dept_name,
            email: self.email,
            id: self.id,
            login_date: self.login_date,
            login_ip: self.login_ip,
            mobile: self.mobile,
            nickname: self.nickname,
            post_ids: self.post_ids,
            remark: self.remark,
            sex: self.sex,
            status: self.status,
            username: self.username,
        }
    }
}

impl From<Model> for UserVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            nickname: value.nickname,
            avatar: value.avatar,
            dept_id: value.dept_id,
            username: value.username,
            email: value.email,
        }
    }
}

impl From<Model> for UserRespVO {
    fn from(value: Model) -> Self {
        Self {
            avatar: value.avatar,
            create_time: value.create_time,
            dept_id: value.dept_id,
            dept_name: None,
            email: value.email,
            id: value.id,
            login_date: value.login_date,
            login_ip: value.login_ip,
            mobile: value.mobile,
            nickname: value.nickname,
            post_ids: value.post_ids,
            remark: value.remark,
            sex: value.sex,
            status: value.status,
            username: value.username,
        }
    }
}
