//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::utils::templates::parse_template_content_params;
use daoyi_common_support::vo::system_vo::{
    MailTemplateRespVO, MailTemplateSaveReqVO, MailTemplateSimpleRespVO, MailTemplateUpdateReqVO,
};
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use sea_orm::{Set, Unchanged};
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_mail_template")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub code: String,
    pub account_id: String,
    pub nickname: Option<String>,
    pub title: String,
    pub content: String,
    pub params: Vec<String>,
    pub status: CommonStatusEnum,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<MailTemplateSaveReqVO> for ActiveModel {
    fn from(value: MailTemplateSaveReqVO) -> Self {
        let params = parse_template_content_params(&value.content);
        Self {
            account_id: Set(value.account_id),
            code: Set(value.code),
            content: Set(value.content),
            name: Set(value.name),
            nickname: Set(value.nickname),
            remark: Set(value.remark),
            status: Set(value.status),
            title: Set(value.title),
            params: Set(params),
            ..Default::default()
        }
    }
}

impl From<MailTemplateUpdateReqVO> for ActiveModel {
    fn from(value: MailTemplateUpdateReqVO) -> Self {
        let params = parse_template_content_params(&value.content);
        Self {
            id: Unchanged(value.id),
            account_id: Set(value.account_id),
            code: Set(value.code),
            content: Set(value.content),
            name: Set(value.name),
            nickname: Set(value.nickname),
            remark: Set(value.remark),
            status: Set(value.status),
            title: Set(value.title),
            params: Set(params),
            ..Default::default()
        }
    }
}

impl From<Model> for MailTemplateRespVO {
    fn from(value: Model) -> Self {
        Self {
            account_id: value.account_id,
            code: value.code,
            content: value.content,
            id: value.id,
            nickname: value.nickname,
            status: value.status,
            title: value.title,
            remark: value.remark,
            name: value.name,
            params: value.params,
            create_time: value.create_time,
        }
    }
}

impl From<Model> for MailTemplateSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            name: value.name,
        }
    }
}
