//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::models::system::TenantPackageRespVo;
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_tenant_package")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub status: CommonStatusEnum,
    pub remark: Option<String>,
    pub menu_ids: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for TenantPackageRespVo {
    fn from(value: Model) -> Self {
        Self {
            create_time: value.create_time,
            id: value.id,
            name: value.name,
            status: value.status,
            remark: value.remark,
            menu_ids: value.menu_ids,
        }
    }
}
