//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::CommonStatusEnum;
use daoyi_common_support::vo::system_vo::DictDataSimpleRespVO;
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_dict_data")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub sort: i32,
    pub label: String,
    pub value: String,
    pub dict_type: String,
    pub status: CommonStatusEnum,
    pub color_type: Option<String>,
    pub css_class: Option<String>,
    pub remark: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for DictDataSimpleRespVO {
    fn from(value: Model) -> Self {
        Self {
            dict_type: value.dict_type,
            label: value.label,
            value: value.value,
            color_type: value.color_type,
            css_class: value.css_class,
        }
    }
}