//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_common_support::enumeration::{SmsChannelEnum, SmsTemplateTypeEnum};
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_sms_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub channel_id: String,
    pub channel_code: SmsChannelEnum,
    pub template_id: String,
    pub template_code: String,
    pub template_type: SmsTemplateTypeEnum,
    pub template_content: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub template_params: Json,
    pub api_template_id: String,
    pub mobile: String,
    pub user_id: Option<String>,
    pub user_type: Option<String>,
    pub send_status: i16,
    pub send_time: Option<DateTime>,
    pub api_send_code: Option<String>,
    pub api_send_msg: Option<String>,
    pub api_request_id: Option<String>,
    pub api_serial_no: Option<String>,
    pub receive_status: bool,
    pub receive_time: Option<DateTime>,
    pub api_receive_code: Option<String>,
    pub api_receive_msg: Option<String>,
}
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

