//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_macros::DaoyiActiveModelBehavior;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_users")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub password: String,
    pub nickname: String,
    pub remark: Option<String>,
    pub dept_id: Option<String>,
    pub post_ids: Option<Vec<String>>,
    pub email: Option<String>,
    pub mobile: Option<String>,
    pub sex: Option<String>,
    pub avatar: Option<String>,
    pub status: String,
    pub login_ip: Option<String>,
    pub login_date: Option<DateTime>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}