//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use daoyi_common_support::enumeration::CommonStatusEnum;

#[daoyi_model]
#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_sms_template")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: String,
    pub status: CommonStatusEnum,
    pub code: String,
    pub name: String,
    pub content: String,
    pub params: String,
    pub remark: Option<String>,
    pub api_template_id: String,
    pub channel_id: String,
    pub channel_code: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
