//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{NotifyTemplateTypeEnum, UserTypeEnum};
use daoyi_common_support::vo::system_vo::NotifyMessageRespVo;
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_notify_message")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub user_type: UserTypeEnum,
    pub template_id: String,
    pub template_code: String,
    pub template_nickname: String,
    pub template_content: String,
    pub template_type: NotifyTemplateTypeEnum,
    #[sea_orm(column_type = "JsonBinary")]
    pub template_params: Json,
    pub read_status: bool,
    pub read_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for NotifyMessageRespVo {
    fn from(value: Model) -> Self {
        Self {
            id: value.id,
            user_id: value.user_id,
            user_type: value.user_type,
            template_id: value.template_id,
            template_code: value.template_code,
            template_nickname: value.template_nickname,
            template_content: value.template_content,
            template_type: value.template_type,
            template_params: value.template_params,
            read_status: value.read_status,
            read_time: value.read_time,
            create_time: value.create_time,
        }
    }
}
