//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::{MailSendStatusEnum, UserTypeEnum};
use daoyi_common_support::vo::system_vo::MailLogRespVO;
use daoyi_macros::{DaoyiActiveModelBehavior, daoyi_model};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "system", table_name = "system_mail_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub user_type: UserTypeEnum,
    pub to_mails: Vec<String>,
    pub cc_mails: Vec<String>,
    pub bcc_mails: Vec<String>,
    pub account_id: String,
    pub from_mail: String,
    pub template_id: String,
    pub template_code: String,
    pub template_nickname: Option<String>,
    pub template_title: String,
    pub template_content: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub template_params: Json,
    pub send_status: MailSendStatusEnum,
    pub send_time: Option<DateTime>,
    pub send_message_id: Option<String>,
    pub send_exception: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<Model> for MailLogRespVO {
    fn from(value: Model) -> Self {
        Self {
            account_id: value.account_id,
            bcc_mails: value.bcc_mails,
            cc_mails: value.cc_mails,
            from_mail: value.from_mail,
            id: value.id,
            send_exception: value.send_exception,
            send_message_id: value.send_message_id,
            send_status: value.send_status,
            send_time: value.send_time,
            template_code: value.template_code,
            template_content: value.template_content,
            template_id: value.template_id,
            template_nickname: value.template_nickname,
            template_title: value.template_title,
            to_mails: value.to_mails,
            user_id: value.user_id,
            user_type: value.user_type,
            create_time: value.create_time,
            template_params: value.template_params,
        }
    }
}
