//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::system_access_token::Entity as SystemAccessToken;
pub use super::system_dept::Entity as SystemDept;
pub use super::system_dict_data::Entity as SystemDictData;
pub use super::system_dict_type::Entity as SystemDictType;
pub use super::system_mail_account::Entity as SystemMailAccount;
pub use super::system_mail_log::Entity as SystemMailLog;
pub use super::system_mail_template::Entity as SystemMailTemplate;
pub use super::system_menu::Entity as SystemMenu;
pub use super::system_notice::Entity as SystemNotice;
pub use super::system_notify_message::Entity as SystemNotifyMessage;
pub use super::system_notify_template::Entity as SystemNotifyTemplate;
pub use super::system_post::Entity as SystemPost;
pub use super::system_role::Entity as SystemRole;
pub use super::system_role_menu::Entity as SystemRoleMenu;
pub use super::system_sms_channel::Entity as SystemSmsChannel;
pub use super::system_sms_code::Entity as SystemSmsCode;
pub use super::system_sms_log::Entity as SystemSmsLog;
pub use super::system_sms_template::Entity as SystemSmsTemplate;
pub use super::system_tenant::Entity as SystemTenant;
pub use super::system_tenant_package::Entity as SystemTenantPackage;
pub use super::system_user_post::Entity as SystemUserPost;
pub use super::system_user_role::Entity as SystemUserRole;
pub use super::system_users::Entity as SystemUsers;
