//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "system", table_name = "system_sms_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub channel_id: String,
    pub channel_code: String,
    pub template_id: String,
    pub template_code: String,
    pub template_type: String,
    pub template_content: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub template_params: Json,
    pub api_template_id: String,
    pub mobile: String,
    pub user_id: Option<String>,
    pub user_type: Option<String>,
    pub send_status: bool,
    pub send_time: Option<DateTime>,
    pub api_send_code: Option<String>,
    pub api_send_msg: Option<String>,
    pub api_request_id: Option<String>,
    pub api_serial_no: Option<String>,
    pub receive_status: bool,
    pub receive_time: Option<DateTime>,
    pub api_receive_code: Option<String>,
    pub api_receive_msg: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
