//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_call_speech_text")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: Option<String>,
    pub call_id: Option<String>,
    pub device_id: Option<String>,
    pub device_type: Option<String>,
    pub speech_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub speech_text: Option<String>,
    pub asr_product: Option<String>,
    pub intention: Option<String>,
    pub quality_status: Option<i32>,
    pub status: String,
    pub month: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
