//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_company")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub id_path: Option<String>,
    pub pid: Option<String>,
    pub company_code: String,
    pub gmt: Option<i32>,
    pub contact: Option<String>,
    pub phone: Option<String>,
    pub balance: Option<i64>,
    pub bill_type: Option<String>,
    pub pay_type: Option<String>,
    pub hidden_customer: Option<String>,
    pub secret_type: Option<String>,
    pub secret_key: Option<String>,
    pub ivr_limit: Option<i32>,
    pub agent_limit: Option<i32>,
    pub group_limit: Option<i32>,
    pub group_agent_limit: Option<i32>,
    pub record_storage: Option<i32>,
    pub notify_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext1: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext2: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext3: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext4: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ext5: Option<String>,
    pub status: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
