//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_stat_day_agent")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub agent_key: String,
    pub agent_name: Option<String>,
    pub stat_time: DateTime,
    pub callout_cnt: Option<i64>,
    pub callout_answer_cnt: Option<i64>,
    pub callin_cnt: Option<i64>,
    pub callin_answer_cnt: Option<i64>,
    pub login_cnt: Option<i64>,
    pub ready_cnt: Option<i64>,
    pub not_ready_cnt: Option<i64>,
    pub after_cnt: Option<i64>,
    pub login_time: Option<i64>,
    pub ready_time: Option<i64>,
    pub not_ready_time: Option<i64>,
    pub busy_time: Option<i64>,
    pub after_time: Option<i64>,
    pub talk_time: Option<i64>,
    pub callin_talk_time: Option<i64>,
    pub callout_talk_time: Option<i64>,
    pub status: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
