//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_agent")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub agent_id: Option<String>,
    pub agent_key: String,
    pub agent_name: Option<String>,
    pub agent_code: Option<String>,
    pub agent_type: String,
    pub passwd: String,
    pub sip_phone: Option<String>,
    pub record: Option<bool>,
    pub group_id: Option<String>,
    pub agent_online: Option<i32>,
    pub after_interval: Option<i32>,
    pub display: Option<String>,
    pub ring_time: Option<i32>,
    pub host: Option<String>,
    pub ext1: Option<String>,
    pub ext2: Option<String>,
    pub ext3: Option<String>,
    pub state: Option<String>,
    pub status: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
