//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_call_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub call_id: String,
    pub caller_display: Option<String>,
    pub caller: Option<String>,
    pub called_display: Option<String>,
    pub called: Option<String>,
    pub number_location: Option<String>,
    pub agent_key: Option<String>,
    pub agent_name: Option<String>,
    pub group_id: Option<String>,
    pub login_type: Option<String>,
    pub task_id: Option<String>,
    pub ivr_id: Option<String>,
    pub bot_id: Option<String>,
    pub call_time: Option<DateTime>,
    pub answer_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub call_type: Option<String>,
    pub direction: Option<String>,
    pub answer_flag: Option<i32>,
    pub wait_time: Option<i64>,
    pub answer_count: Option<i32>,
    pub hangup_dir: Option<i32>,
    pub sdk_hangup: Option<i32>,
    pub hangup_code: Option<i32>,
    pub media_host: Option<String>,
    pub cti_host: Option<String>,
    pub client_host: Option<String>,
    pub record: Option<String>,
    pub record2: Option<String>,
    pub record3: Option<String>,
    pub record_type: Option<String>,
    pub record_start_time: Option<DateTime>,
    pub record_time: Option<i64>,
    pub talk_time: Option<i64>,
    pub frist_queue_time: Option<DateTime>,
    pub queue_start_time: Option<DateTime>,
    pub queue_end_time: Option<DateTime>,
    pub month_time: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub follow_data: Option<String>,
    pub uuid1: Option<String>,
    pub uuid2: Option<String>,
    pub ext1: Option<String>,
    pub ext2: Option<String>,
    pub ext3: Option<String>,
    pub status: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
