//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_group")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub name: String,
    pub after_interval: Option<i32>,
    pub caller_display_id: Option<String>,
    pub called_display_id: Option<String>,
    pub record_type: Option<String>,
    pub level_value: Option<i32>,
    pub tts_engine: Option<i64>,
    pub play_content: Option<String>,
    pub evaluate: Option<bool>,
    pub queue_play: Option<i64>,
    pub transfer_play: Option<i64>,
    pub call_time_out: Option<i32>,
    pub group_type: Option<String>,
    pub notify_position: Option<i32>,
    pub notify_rate: Option<i32>,
    pub notify_content: Option<String>,
    pub call_memory: Option<i32>,
    pub ext1: Option<String>,
    pub ext2: Option<String>,
    pub ext3: Option<String>,
    pub ext4: Option<String>,
    pub ext5: Option<String>,
    pub status: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
