//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_route_call")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub cti_route_group_id: String,
    pub route_num: String,
    pub num_max: Option<i32>,
    pub num_min: Option<i32>,
    pub caller_change: Option<i32>,
    pub caller_change_num: Option<String>,
    pub called_change: Option<i32>,
    pub called_change_num: Option<String>,
    pub status: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
