//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "cti", table_name = "cti_agent_state_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub company_id: String,
    pub group_id: Option<String>,
    pub agent_id: Option<String>,
    pub agent_key: Option<String>,
    pub agent_name: Option<String>,
    pub call_id: Option<String>,
    pub login_type: Option<String>,
    pub work_type: Option<String>,
    pub host: Option<String>,
    pub remote_address: Option<String>,
    pub before_state: Option<String>,
    pub before_time: Option<DateTime>,
    pub state: Option<String>,
    pub state_time: Option<DateTime>,
    pub duration: Option<i32>,
    pub busy_desc: Option<String>,
    pub status: String,
    pub month: Option<String>,
    pub ext1: Option<String>,
    pub ext2: Option<String>,
    pub ext3: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
