//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "infra", table_name = "infra_codegen_table")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub data_source_config_id: String,
    pub scene: String,
    pub table_name: String,
    pub table_comment: String,
    pub remark: Option<String>,
    pub module_name: String,
    pub business_name: String,
    pub class_name: String,
    pub class_comment: String,
    pub author: String,
    pub template_type: String,
    pub front_type: String,
    pub parent_menu_id: Option<String>,
    pub master_table_id: Option<String>,
    pub sub_join_column_id: Option<String>,
    pub sub_join_many: Option<bool>,
    pub tree_parent_column_id: Option<String>,
    pub tree_name_column_id: Option<String>,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
