//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "infra", table_name = "infra_codegen_column")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub table_id: String,
    pub column_name: String,
    pub data_type: String,
    pub column_comment: String,
    pub nullable: bool,
    pub primary_key: bool,
    pub ordinal_position: i32,
    pub java_type: String,
    pub java_field: String,
    pub dict_type: Option<String>,
    pub example: Option<String>,
    pub create_operation: bool,
    pub update_operation: bool,
    pub list_operation: bool,
    pub list_operation_condition: String,
    pub list_operation_result: bool,
    pub html_type: String,
    pub creator: Option<String>,
    pub create_time: DateTime,
    pub updater: Option<String>,
    pub update_time: DateTime,
    pub deleted: bool,
    pub tenant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
