[package]
name = "daoyi-api-infra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
daoyi-common-support.workspace = true
axum.workspace = true
daoyi-entity-infra.workspace = true
tracing.workspace = true
mime_guess.workspace = true
urlencoding.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true
xid.workspace = true
async-trait = "0.1"