//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use daoyi_common_support::enumeration::FileStorageEnum;
use daoyi_common_support::vo::infra_vo::FileConfigSaveReqVo;
use daoyi_macros::{daoyi_model, DaoyiActiveModelBehavior};
use sea_orm::entity::prelude::*;
use sea_orm::Set;
use serde::{Deserialize, Serialize};

#[daoyi_model]
#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, DaoyiActiveModelBehavior,
)]
#[sea_orm(schema_name = "infra", table_name = "infra_file_config")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub storage: FileStorageEnum,
    pub remark: Option<String>,
    pub master: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl From<FileConfigSaveReqVo> for ActiveModel {
    fn from(value: FileConfigSaveReqVo) -> Self {
        let mut active_model = ActiveModel::new();
        active_model.name = Set(value.name);
        active_model.storage = Set(value.storage);
        active_model.remark = Set(value.remark);
        active_model.config = Set(value.config);
        active_model.master = Set(false);
        active_model
    }
}
